---
# Source: kcontainer-reefer-simulator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-kcontainer-reefer-simulator
  labels:
    app.kubernetes.io/name: kcontainer-reefer-simulator
    helm.sh/chart: kcontainer-reefer-simulator-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kcontainer-reefer-simulator
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kcontainer-reefer-simulator
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: kcontainer-reefer-simulator
          image: "ibmcase/kcontainer-reefer-simulator:0.1.7"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            null
          env:
            - name: PORT
              value: "8080"
            - name: APPLICATION_NAME
              value: "release-name"
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: "demo-kafka-brokers"
                  key: brokers
            - name: TELEMETRY_TOPIC
              value: "eda-integration-reeferTelemetries"
            - name: CONTAINER_TOPIC
              value: "eda-integration-containers"
            - name: KAFKA_APIKEY
              valueFrom:
                secretKeyRef:
                  name: "demo-es-apikey"
                  key: binding
